## Model answers_Assignment 2

#Q1:

In [1]:
def best_fit(x, y):

    xbar = sum(x)/len(x)
    ybar = sum(y)/len(y)
    n = len(x) # or len(y)

    numer = sum([xi*yi for xi,yi in zip(x, y)]) - n * xbar * ybar
    denum = sum([xi**2 for xi in x]) - n * xbar**2

    b = numer / denum
    a = ybar - b * xbar

    print('best fit line:\ny = {:.4f} + {:.4f}x'.format(a, b))

    return a, b

x = [1, 2, 3, 4, 5]
y = [1, 0.99, 2, 0.98, 0.97]

# solution
a, b = best_fit(x, y)
#best fit line:
#y = 1.21 + -0.01x

best fit line:
y = 1.2090 + -0.0070x


In [2]:
# plot points and fit line of Y as dependent variable

import matplotlib.pyplot as plt
import pylab

plt.scatter(x, y)
yfit = [a + b * xi for xi in x]
plt.plot(x, yfit)
plt.show()

In [3]:
def best_fit1(y, x):

    ybar = sum(y)/len(y)
    xbar = sum(x)/len(x)
    n = len(y) # or len(x)

    numer = sum([yi*xi for yi,xi in zip(y, x)]) - n * ybar * xbar
    denum = sum([yi**2 for yi in y]) - n * ybar**2

    b = numer / denum
    a = xbar - b * ybar

    print('best fit line:\nx = {:.4f} + {:.4f}y'.format(a, b))

    return a, b

c, d = best_fit1(y, x)

best fit line:
x = 3.1008 + -0.0849y


In [4]:
# plot points and fit line of Y as independent variable

plt.scatter(y, x)
xfit = [c + d * yi for yi in y]
plt.plot(y, xfit)
plt.show()

In [5]:
from scipy import stats

gradient, intercept, r_value, p_value, std_err = stats.linregress(x,y)
print "Gradient and intercept", gradient, intercept
#Gradient and intercept -0.007 1.209
print "R-squared", r_value**2
#R-squared 0.000594169859824
print "p-value", p_value
#p-value 0.968967096273

Gradient and intercept -0.007 1.209
R-squared 0.000594169859824
p-value 0.968967096273


In [6]:
gradient, intercept, r_value, p_value, std_err = stats.linregress(y,x)
print "Gradient and intercept", gradient, intercept
#Gradient and intercept -0.0848814085463 3.10083911335
print "R-squared", r_value**2
#R-squared 0.000594169859824
print "p-value", p_value
#p-value 0.968967096273

Gradient and intercept -0.0848814085463 3.10083911335
R-squared 0.000594169859824
p-value 0.968967096273


In [7]:
# Remove the third point (3, 2)
x1 = [1, 2, 4, 5]
y1 = [1, 0.99, 0.98, 0.97]

# solution
a, b = best_fit(x1, y1)

#best fit line:
#y1 = 1.0060 + -0.0070x1

best fit line:
y = 1.0060 + -0.0070x


In [8]:
c, d = best_fit1(y1, x1)
#best fit line:
#x1 = 140.9000 + -140.0000y1

best fit line:
x = 140.9000 + -140.0000y


In [9]:
plt.scatter(x1, y1)
y1fit = [a + b * x1i for x1i in x1]
plt.plot(x1, y1fit)
plt.show()

In [10]:
plt.scatter(y1, x1)
x1fit = [c + d * y1i for y1i in y1]
plt.plot(y1, x1fit)
plt.show()

#Q2:

In [11]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors

In [12]:
# Generate 100k datapoints from normal distribution with mean 1 and standard deviation 0.01.
# Another set of 5 anomalous datapoints from normal distribution with mean 0.1 and standard deviation 0.001.
np.random.seed(12121)

normal_1 =  np.random.normal(loc= 1, scale= 0.01, size=(100000, 2))
normal_2 =  np.random.normal(loc= 0.1, scale= 0.001, size=(5, 2))

In [13]:
# Plot data to show differences between normal and outlier data
normal_plot = plt.scatter(normal_1[:100000, 0], normal_1[:100000, 1], c='blue')
anomaly_plot = plt.scatter(normal_2[:5, 0], normal_2[:5, 1], c='red')
plt.show()

In [14]:
# Combining both groups together to get total (100k+5) datapoints:
all_data = np.concatenate((normal_1, normal_2))

In [15]:
## To check whether 1-NN approach can find the anomalies we calculated the distances and then sorted them in descending order
 
nn_fit = NearestNeighbors(n_neighbors=2).fit(all_data)
distances, indices = nn_fit.kneighbors()

#The maximum distance between any two datapoints in 1-nearest neighbourhood is:
np.amax(distances)

0.0086101459505631382

In [16]:
nn_fit.kneighbors(all_data)

(array([[  0.00000000e+00,   1.55496922e-04],
        [  0.00000000e+00,   3.72730046e-05],
        [  0.00000000e+00,   2.81651848e-05],
        ..., 
        [  0.00000000e+00,   6.42722597e-04],
        [  0.00000000e+00,   1.80212013e-04],
        [  0.00000000e+00,   1.80212013e-04]]), array([[     0,  52821],
        [     1,  70370],
        [     2,  74595],
        ..., 
        [100002, 100003],
        [100003, 100004],
        [100004, 100003]]))

In [17]:
## To check whether 10-NN approach can find the anomalies we calculated the distances and then sorted them in descending order

nn_fit = NearestNeighbors(n_neighbors=11).fit(all_data)
distances, indices = nn_fit.kneighbors()

#The maximum distance between any two datapoints in 10-nearest neighbourhood is:
np.amax(distances)

1.2347653187541763

In [18]:
nn_fit.kneighbors(all_data)

(array([[  0.00000000e+00,   1.55496922e-04,   2.35498643e-04, ...,
           3.12313623e-04,   3.12604020e-04,   3.22526390e-04],
        [  0.00000000e+00,   3.72730046e-05,   3.80533975e-05, ...,
           2.73212926e-04,   2.81085402e-04,   2.97430195e-04],
        [  0.00000000e+00,   2.81651848e-05,   1.00808949e-04, ...,
           1.56325532e-04,   1.61408840e-04,   1.67866629e-04],
        ..., 
        [  0.00000000e+00,   6.42722597e-04,   6.64049921e-04, ...,
           1.23287927e+00,   1.23365617e+00,   1.23466313e+00],
        [  0.00000000e+00,   1.80212013e-04,   5.70330065e-04, ...,
           1.23238732e+00,   1.23316059e+00,   1.23416699e+00],
        [  0.00000000e+00,   1.80212013e-04,   6.64049921e-04, ...,
           1.23250605e+00,   1.23327811e+00,   1.23428432e+00]]),
 array([[     0,  52821,  66453, ...,  41385,  29065,  26580],
        [     1,  70370,  30437, ...,   9512,  40718,  10644],
        [     2,  74595,  24222, ...,  78020,  31667,  83327],
   

## Hence for k = 10-NN, these distances sorted in decreasing order have a sharp drop after the first 5 points and these 5 points are the ones which we have generated as anomalies (i.e. All 5 are correctly identified). 

## For 1-NN, the distances will likely have no clear threshold cutoff and any cutoff will likely result in many false positives.